server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:read-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  h2:
    console.enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.common

