server:
  port: 9001
spring:
  datasource:
    url: jdbc:h2:mem:write-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

